version: '3.8'

services:
  primary:
    build: .
    ports:
      - 38080:8080
    environment:
      - ReplicationLog__MaxAppendDelayMs=0
      - ReplicationLog__Secondaries__0=http://secondary1:8080
      - ReplicationLog__Secondaries__1=http://secondary2:8080

  secondary1:
    build: .    
    ports:
      - 38081:8080
    environment:
      - ReplicationLog__MaxAppendDelayMs=20000
    depends_on: 
      - primary

  secondary2:
    build: .
    ports:
      - 38082:8080
    environment:
      - ReplicationLog__MaxAppendDelayMs=20000
    depends_on: 
      - primary
  